title: Janbless Mendoza
logo: /assets/img/headshot_circle.png(https://scontent.fcrk1-1.fna.fbcdn.net/v/t39.30808-6/480713659_615082744710743_4198503250154753629_n.jpg?_nc_cat=107&ccb=1-7&_nc_sid=6ee11a&_nc_eui2=AeE2vJ5EBQeQo1W0Xoz6ltgXVqgRM4XWiMZWqBEzhdaIxnWetlA9lIMNP_edaJyb_ueAYM-pe2qSi6JNgU-_8tsX&_nc_ohc=mNZcg7HXi30Q7kNvgEaJ8NG&_nc_oc=AdgG5rk8IhRwnWlRHFO04M-Tg-2EQLclHCn7hi8-GPpmvJ_H0VeaAtmrgtBmLa9a7d8&_nc_zt=23&_nc_ht=scontent.fcrk1-1.fna&_nc_gid=AR2Ffrwx-mxZNiGFxySXvKe&oh=00_AYC2cNyrBLQDfPNGWfmdhN9O0prpN3aB7AfCrHyB7Ry7Fg&oe=67CE2483)

theme: jekyll-theme-minimal
